name: Tests

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda path windows
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        echo "$CONDA" >> $GITHUB_PATH
        echo "$CONDA/Scripts" >> $GITHUB_PATH
        echo "$CONDA/Library" >> $GITHUB_PATH
        echo "$CONDA/Library/bin" >> $GITHUB_PATH
        echo "$CONDA/Library/mingw-w64/bin" >> $GITHUB_PATH
        
    - name: Add conda to system path
      if: ${{ runner.os == 'Linux' }}
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        python --version
    - name: chwon on macOS
      if: ${{ runner.os == 'macOS' }}
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
        sudo chown -R $UID:$GID $CONDA 
    - name: Install dependencies
      shell: bash
      run: |
        conda install --yes pip
        pip install coverage
        pip install coveralls
        conda config --append channels conda-forge
        conda config --append channels ingeotec
        conda install --yes numpy scipy scikit-learn nltk nose b4msa evodag conceptmodelling cython evomsa cartopy pandas
        python setup.py build_ext --inplace
    - name: Tests on Linux
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        which python
        python --version
        which coverage
        coverage run setup.py nosetests --with-doctest
    - name: Tests on macOS and Windows
      shell: bash
      if: ${{ runner.os != 'Linux' }}
      run: |
        nosetests --verbose text_models/tests
    - name: coveralls
      if: ${{ runner.os == 'Linux' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github