name: Tests

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Owner
      if: ${{ runner.os == 'macOS' }}
      run: |
        sudo chown -R $UID:$GID $CONDA 
    - name: Install dependencies
      run: |
        conda install --yes pip
        pip install coverage
        pip install coveralls
        conda config --append channels conda-forge
        conda config --append channels ingeotec
        conda install --yes numpy scipy scikit-learn nltk nose b4msa evodag conceptmodelling cython evomsa cartopy pandas
        python setup.py build_ext --inplace
    - name: Test
      run: |
        which python
        python --version
        which coverage
        coverage run setup.py nosetests --with-doctest
    - name: coveralls
      if: ${{ runner.os == 'Linux' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github