name: Tests

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python     
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        conda install --yes pip
        pip install coverage
        pip install coveralls
        conda config --append channels conda-forge
        conda config --append channels ingeotec
        conda install --yes numpy scipy scikit-learn nltk nose b4msa evodag conceptmodelling cython evomsa cartopy pandas
        python setup.py build_ext --inplace
    - name: Tests on Linux
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        which python
        python --version
        which coverage
        coverage run setup.py nosetests --with-doctest
    - name: Tests on macOS and Windows
      shell: bash
      if: ${{ runner.os != 'Linux' }}
      run: |
        nosetests --verbose text_models/tests
    - name: coveralls
      if: ${{ runner.os == 'Linux' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls --service=github